### ISSUE TITLE
About the use of deep-forest 

### ISSUE THREAD

**Issue by xuyxu** [davidlkl/Insurance-Pricing-Game#1]
Hi @davidlkl, congrats on winning the competition, and thanks for trying out the deep forest package ;-)

It looks like that the `CascadeForestRegressor` was not used in your final solution, right? (since the `df_regressor` was commented out in [train.py](https://github.com/davidlkl/Insurance-Pricing-Game/blob/main/train.py)). Therefore, we will appreciate it very much if you could tell us the reason, such as adding it simply makes the performance worse, or it takes forever to finish training. Thanks!

**Comment by davidlkl** [comment]
Hi,

DeepForest was used as part of my final solution!

Its just that it takes a bit long to run (~10mins per fold), so I just commented it out when running some experiments to prepare for my presentation.

For your information, out of the 7 base models (GLM, XGB, Catboost, LGBM, DeepForest, NN, Baynesian_NN), Deepforest is slightly worse than the others 6. Interestingly, it does not have strong correlation (0.94) with the other GBMs (e.g. XGB), while among the GBMs they will have 0.97-0.98 in correlation. So, the final stack model performance is improved a bit after including DeepForest.

Thanks!

**Comment by xuyxu** [comment]
Glad to hear that @davidlkl 😄. You could think of Deep forest as a random forest based ensemble, and it is reasonable that deep forest has more different predictions compared to the predictions between GBDTs.

Once again, congrats! Another question is that are you willing to share your winning solution in our community, the link to this repo will be posted in a webpage in our documentation. More details are available in this [issue](https://github.com/LAMDA-NJU/Deep-Forest/issues/55).

**Comment by davidlkl** [comment]
No problem! Glad to have my solution shared!
